# -*- coding: utf-8 -*-
"""chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JmavhDPBJ4_crwzUb9IiJbkDTjdvxfLR
"""

import streamlit as st
import os

from langchain_openai import ChatOpenAI
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_chroma import Chroma
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain.tools import tool
from langchain_core.documents import Document
from langchain.agents import create_agent
from langgraph.checkpoint.memory import InMemorySaver

import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin, urlparse

# -----------------------
# PAGE CONFIG
# -----------------------
st.set_page_config(
    page_title="SCRI Chatbot",
    page_icon="🤖",
    layout="wide"
)

st.title("🤖 SCRI AI Assistant")
st.markdown("Ask anything about SCRI (PDF + Website Knowledge)")

# -----------------------
# LOAD MODEL
# -----------------------
load_dotenv()

GROQ_API_KEY = "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"

GROQ_API_KEY = st.secrets["GROQ_API_KEY"]

llm = ChatOpenAI(
    api_key=GROQ_API_KEY,
    base_url="https://api.groq.com/openai/v1",
    model="openai/gpt-oss-20b",
    temperature=0.2,
)

# -----------------------
# LOAD PDF + VECTOR DB
# -----------------------
@st.cache_resource
def setup_vectorstore():

    loader = PyPDFLoader("SCRI.pdf")
    documents = loader.load()

    splitter = RecursiveCharacterTextSplitter(
        chunk_size=500,
        chunk_overlap=100,
    )

    docs = splitter.split_documents(documents)

    embeddings = HuggingFaceEmbeddings(
        model_name="sentence-transformers/all-MiniLM-L6-v2"
    )

    vector_store = Chroma(
        collection_name="NLP_Project",
        embedding_function=embeddings,
        persist_directory="./chroma_langchain_db",
    )

    vector_store.add_documents(docs)

    return vector_store

vector_store = setup_vectorstore()

# -----------------------
# RETRIEVE TOOL
# -----------------------
@tool
def retrieve_context(query: str) -> str:
    retrieved_docs = vector_store.similarity_search(query, k=2)

    serialized = "\n\n".join(
        f"Source: {doc.metadata}\nContent: {doc.page_content}"
        for doc in retrieved_docs
    )

    return serialized

# -----------------------
# WEBSITE CRAWLER
# -----------------------
def crawl_website_for_text(base_url: str, max_pages: int = 10):
    visited = set()
    to_visit = [base_url]
    documents = []

    while to_visit and len(visited) < max_pages:
        current_url = to_visit.pop()

        if current_url in visited:
            continue

        visited.add(current_url)

        try:
            response = requests.get(current_url, timeout=5)
            if response.status_code != 200:
                continue

            soup = BeautifulSoup(response.text, "html.parser")

            for tag in soup(["script", "style", "noscript"]):
                tag.decompose()

            text = soup.get_text(separator=" ", strip=True)

            if len(text) < 200:
                continue

            documents.append(
                Document(page_content=text, metadata={"source": current_url})
            )

            for link in soup.find_all("a"):
                href = link.get("href")
                if not href:
                    continue

                full_url = urljoin(current_url, href)

                if urlparse(full_url).netloc == urlparse(base_url).netloc:
                    to_visit.append(full_url)

        except:
            continue

    return documents


@tool
def crawl_and_add(base_url: str) -> str:
    docs = crawl_website_for_text(base_url)

    if not docs:
        return "No usable content found."

    splitter = RecursiveCharacterTextSplitter(
        chunk_size=500,
        chunk_overlap=100
    )

    chunks = splitter.split_documents(docs)

    vector_store.add_documents(chunks)

    return "Website content stored successfully."


# -----------------------
# CREATE AGENT
# -----------------------
tools = [retrieve_context, crawl_and_add]

agent = create_agent(
    llm,
    tools,
    checkpointer=InMemorySaver(),
    system_prompt=(
        "Use retrieve_context tool for SCRI related questions."
    )
)

# -----------------------
# SESSION MEMORY
# -----------------------
if "messages" not in st.session_state:
    st.session_state.messages = []

# Display chat history
for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])

# -----------------------
# USER INPUT
# -----------------------
if prompt := st.chat_input("Ask your question..."):

    # Show user message
    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)

    # Get agent response
    response = agent.invoke(
        {"messages": st.session_state.messages},
        {"configurable": {"thread_id": "1"}},
    )

    reply = response["messages"][-1].content

    # Show bot message
    st.session_state.messages.append({"role": "assistant", "content": reply})
    with st.chat_message("assistant"):
        st.markdown(reply)

# -----------------------
# SIDEBAR
# -----------------------
st.sidebar.title("⚙️ Controls")

if st.sidebar.button("Crawl SCRI Website"):
    with st.spinner("Crawling website..."):
        result = crawl_and_add("https://scri.siu.edu.in/")
    st.sidebar.success(result)

if st.sidebar.button("Clear Chat"):
    st.session_state.messages = []
    st.sidebar.success("Chat cleared!")
